Validation added in addToCart for quantity and available stock
lunarphp/livewire-starter-kit pull request #74
Opened 2023-09-15 17:11 UTC by sazzadh88

```addToCart``` function  doesn't check for stock available for selected variants. So it's required to check the entered ```quantity``` & stock available.

2023-09-15 23:44 UTC, sazzadh88 commented
sdfsdff

2023-09-17 05:31 UTC, sazzadh88 commented
@glennjacobs Please review it.

2023-09-29 08:07 UTC, alecritson requested changes
Thanks @sazzadh88 just a small point then I think this is good to go :)

2023-09-29 08:07 UTC, alecritson commented on app/Http/Livewire/Components/AddToCart.php
> +        if($this->purchasable->stock < $this->quantity){
I think here we can just return out of the first `if` statement, then we can remove the `else` and carry on as usual.

2023-09-29 08:24 UTC, sazzadh88 commented on app/Http/Livewire/Components/AddToCart.php
> +        if($this->purchasable->stock < $this->quantity){
Yes. Correct.

2023-09-29 08:45 UTC, alecritson approved these changes
Thanks @sazzadh88 will get this merged in :)

2023-09-29 08:45 UTC, merged